In [5]:
# Test _switch_phi_padding_direction function
import torch
from src.model.model import _switch_phi_padding_direction

def test_switch_phi_padding_direction():
    hidden_states = torch.tensor([
        [0, 0, 1, 2, 3],
        [0, 0, 0, 4, 5],
        [1, 2, 3, 4, 5]
    ]).float()
    
    attention_mask = torch.tensor([
        [0, 0, 1, 1, 1],
        [0, 0, 0, 1, 1],
        [1, 1, 1, 1, 1]
    ])
    
    result = _switch_phi_padding_direction(hidden_states, attention_mask)
    
    expected = torch.tensor([
        [1, 2, 3, 0, 0],
        [4, 5, 0, 0, 0],
        [1, 2, 3, 4, 5]
    ]).float()
    
    print("Test case 1:")
    print("Input hidden states:")
    print(hidden_states)
    print("\nInput attention mask:")
    print(attention_mask) 
    print("\nOutput hidden states:")
    print(result)
    print("\nExpected output:")
    print(expected)
    print("\nTest passed:", torch.allclose(result, expected))
    
    batch_size = 2
    seq_len = 4
    hidden_dim = 3
    
    hidden_states = torch.randn(batch_size, seq_len, hidden_dim)
    attention_mask = torch.tensor([
        [1, 1, 0, 0],
        [1, 1, 1, 0]
    ])
    
    result = _switch_phi_padding_direction(hidden_states, attention_mask)
    
    print("\nTest case 2:")
    print("Input shape:", hidden_states.shape)
    print("Output shape:", result.shape)
    print("Shapes match:", result.shape == hidden_states.shape)

test_switch_phi_padding_direction()

Test case 1:
Input hidden states:
tensor([[0., 0., 1., 2., 3.],
        [0., 0., 0., 4., 5.],
        [1., 2., 3., 4., 5.]])

Input attention mask:
tensor([[0, 0, 1, 1, 1],
        [0, 0, 0, 1, 1],
        [1, 1, 1, 1, 1]])

Output hidden states:
tensor([[1., 2., 3., 0., 0.],
        [4., 5., 0., 0., 0.],
        [1., 2., 3., 4., 5.]])

Expected output:
tensor([[1., 2., 3., 0., 0.],
        [4., 5., 0., 0., 0.],
        [1., 2., 3., 4., 5.]])

Test passed: True

Test case 2:
Input shape: torch.Size([2, 4, 3])
Output shape: torch.Size([2, 4, 3])
Shapes match: True
